In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model


#Data preprocessing

In [ ]:
df =pd.read_csv('/content/sample_data/mult_var.csv')
df


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
import math
filling_num=math.floor(df.bedrooms.median())

In [ ]:
df.bedrooms = df.bedrooms.fillna(filling_num)

In [ ]:
df


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

##Train Linear model

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [ ]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [ ]:
reg.intercept_

np.float64(383724.9999999998)

In [ ]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [ ]:
reg.predict([[3000,4,5]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([657250.])

# 2nd exercise


In [4]:
df2 = pd.read_csv("/content/sample_data/hiring.csv")
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
!pip install word2number
from word2number import w2n

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=45b24a58ade808f29f76a3990c244f657d3b2f53329535044e0aa570ef5b67f4
  Stored in directory: /root/.cache/pip/wheels/cd/ef/ae/073b491b14d25e2efafcffca9e16b2ee6d114ec5c643ba4f06
Successfully built word2number


In [6]:
# converting the experience column strings to numbers
df2.experience = df2.experience.apply(lambda x: w2n.word_to_num(str(x)) if str(x).strip().lower() not in ['nan','none'] else 0)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [7]:
# now handling missing value in test_score
df2['test_score(out of 10)']= df2['test_score(out of 10)'].fillna(df2['test_score(out of 10)'].median())
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [8]:
#now capping the testscore column to 10, to fix the sneaky 11
##df2['test_score(out of 10)'] = pd.to_numeric(df2['test_score(out of 10)'])
##df2.loc[df2['test_score(out of 10)']>10,'test_score(out of 10)']=10

# mb, that was experience, keeping this code just to remember how to do such changes

In [9]:
# now our data is ready to be fed into a linear_regression model
reg = linear_model.LinearRegression()
reg.fit(df2[['experience','test_score(out of 10)','interview_score(out of 10)']],df2['salary($)'])

LinearRegression()

In [10]:
reg.predict([[10,10,10]])


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([86376.27365357])

In [11]:
df2


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [12]:
reg.predict([[10,10,1]])


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([66529.11208151])