In [1]:
import numpy as np


In [2]:
python_list = [1,2,3,4,-5]


In [3]:
python_list

[1, 2, 3, 4, -5]

In [5]:
np_array=np.array(python_list)

In [8]:
len(np_array.shape)

1

In [12]:
two_dlist=[[1,2],[3,4]]

In [14]:
np_scndarray=np.array(two_dlist)

In [16]:
len(np_scndarray.shape)

2

In [19]:
newlist=list(range(5))
newlist

[0, 1, 2, 3, 4]

In [20]:
oholist=np.arange(5)
oholist               #directly create a numpy array

array([0, 1, 2, 3, 4])

In [24]:
np.zeros((4,2,1))    #np.ones((2,2)) similar function

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [30]:
np.random.randint(5,size=(2,5))  #randomizes the matrix

array([[2, 0, 2, 4, 3],
       [3, 0, 0, 1, 0]])

In [35]:
a=[1,2,3,4]
arr=np.array(a,dtype=np.int32)  #extra parameter to explicitly convert to a certain datatype
arr.dtype

dtype('int32')

In [46]:
#numpy automatically normalises the datatype while converting a list to a nparray
arr_new=[5.2,4.2,5]
arr2 = np.array(arr2)
arr2.dtype

dtype('float64')

In [51]:
#to convert an array to a datatype
arr3 = arr2.astype(int)
arr2.dtype           #the original array type remains same, astype creates a copy of the array and changes its type
arr3.dtype


dtype('int64')