In [2]:
import numpy as np

In [4]:
arr=np.random.rand(5,5) #rand function generats random numbers from [0.1,1)
arr

array([[0.28112581, 0.47494099, 0.34308058, 0.31963216, 0.38271106],
       [0.90490198, 0.18711255, 0.68837064, 0.46930529, 0.89468129],
       [0.21521378, 0.83264594, 0.73928205, 0.67568562, 0.7025083 ],
       [0.85797437, 0.04959949, 0.6120951 , 0.17531823, 0.01573893],
       [0.32117925, 0.58316209, 0.89550837, 0.47468528, 0.56587241]])

In [6]:
arr[:2] #from starting to row no, 2-1= 1

array([[0.28112581, 0.47494099, 0.34308058, 0.31963216, 0.38271106],
       [0.90490198, 0.18711255, 0.68837064, 0.46930529, 0.89468129]])

In [8]:
arr[2:3] #row index 2 to 3-1=2, so row 2 will be shown

array([[0.21521378, 0.83264594, 0.73928205, 0.67568562, 0.7025083 ]])

In [9]:
arr[:,:4]  #second argumet is for column slicing (after comma)

array([[0.28112581, 0.47494099, 0.34308058, 0.31963216],
       [0.90490198, 0.18711255, 0.68837064, 0.46930529],
       [0.21521378, 0.83264594, 0.73928205, 0.67568562],
       [0.85797437, 0.04959949, 0.6120951 , 0.17531823],
       [0.32117925, 0.58316209, 0.89550837, 0.47468528]])

In [10]:
arr[1,1]  #gives the corresponding element.

np.float64(0.18711255405275296)

In [15]:
arr[:-1]   #slicing from first to last, last means n-1 as we know, so last row is not included

array([[0.28112581, 0.47494099, 0.34308058, 0.31963216, 0.38271106],
       [0.90490198, 0.18711255, 0.68837064, 0.46930529, 0.89468129],
       [0.21521378, 0.83264594, 0.73928205, 0.67568562, 0.7025083 ],
       [0.85797437, 0.04959949, 0.6120951 , 0.17531823, 0.01573893]])

In [3]:
int_arr = np.random.randint(6,size=(6,8))  # make a random integer array
int_arr

array([[1, 1, 0, 3, 5, 2, 0, 1],
       [4, 1, 2, 5, 0, 4, 3, 5],
       [3, 1, 0, 4, 0, 4, 5, 3],
       [5, 3, 2, 1, 0, 1, 1, 2],
       [5, 3, 3, 3, 1, 5, 3, 0],
       [2, 3, 2, 3, 2, 4, 0, 2]])

In [5]:
row = int_arr[0]   # assign one row of the 2d array to a variable
row

array([1, 1, 0, 3, 5, 2, 0, 1])

In [10]:
boolean_arr = (row == 0) | (row == 1) | (row == 2)  # comparing list directly gives a boolean array.

In [11]:
#now our main goal is not to know whether the element is present or not, our goal is to select the true elements and discard false ones.
#we do that by using the boolean array as a mask.
boolean_arr #this is the array

array([ True,  True,  True, False, False,  True,  True,  True])

In [12]:
row[boolean_arr] #original array[boolean array] -> this gives only the true elements,

array([1, 1, 0, 2, 0, 1])