In [1]:
import numpy as np


In [2]:
marks = [[4,2,3,1], [5,9,4,0], [1,9,3,5]] #consider this a matrix of marks of each student in different subjects,

In [4]:
np.array(marks) # maths, biology, physics, chemistry

array([[4, 2, 3, 1],
       [5, 9, 4, 0],
       [1, 9, 3, 5]])

In [5]:
marks[0] #this gave me the marks of one student in all subjects

[4, 2, 3, 1]

In [6]:
marks[0][0], marks[1][0], marks[2][0] #this gave me the marks of students in maths only

(4, 5, 1)

In [9]:
#this is tedious, so we transpose the matrix and now we have subject first matrix, so we can extract the marks of all students in a particular subject
#This is the use of transpose.



4

In [14]:
#traditional method(using loops)

transpose_matrix=[] #make an empty matrix
for i in range(len(marks[0])):
  transpose_matrix.append([]) #adds an empty list here
  for j in range(len(marks)):
    transpose_matrix[i].append(marks[j][i])

transpose_matrix

[[4, 5, 1], [2, 9, 9], [3, 4, 3], [1, 0, 5]]

In [18]:
#using numpy
marks_array = np.array(marks)
transposed = marks_array.T

In [20]:
# marks_array = subjectwise marks for each student
# transposed = marks in a subject per student

#so if im a math teacher who wants to calculate class avg, i will need the second matrix,
transposed.sum(axis=1)/3

array([3.33333333, 6.66666667, 3.33333333, 2.        ])

In [21]:
#the above code gave avg marks in each subject.

In [22]:
marks_array.sum(axis=1)/40*100    #4 subjects of 10 marks each, so this gives percentage of each student

array([25., 45., 45.])

In [23]:
#axis=1 performs row wise operation, axis=0 performs column wise operation, so transpose was not really needed here, but it has other use cases which are not reflected here